sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arseniibylym/docker-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true arseniibylym/docker-travis-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-440556563663'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
