sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t arseniibylym/docker-travis-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true arseniibylym/docker-travis-aws npm run test
